@startuml carmeri
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "users" as users {
  id
  --
  name
  nickname
  email
  password
  image
  postal_code
  address
  created_at
  updated_at
}

entity "categories" as categories {
  id
  --
  category
  created_at
  updated_at
}

entity "conditions" as conditions {
  id
  --
  condition
  created_at
  updated_at
}

entity "category_item" as category_item {
  id
  --
  category_id<<FK>>
  item_id<<FK>>
  created_at
  updated_at
}

entity "items" as items {
  id
  --
  seller_id<<FK>>
  category_id<<FK>>
  name
  price
  is_sold
  image
  brand
  condition
  description
  created_at
  updated_at
}

entity "payment_methods" as payment_methods {
  id
  --
  payment_method
  created_at
  updated_at
}

entity "purchases" as purchases {
  id
  --
  buyer_id<<FK>>
  item_id<<FK>>
  created_at
  updated_at
}

entity "likes" as likes {
  id
  --
  user_id<<FK>>
  item_id<<FK>>
  created_at
  updated_at
}

entity "comments" as comments {
  id
  --
  user_id<<FK>>
  item_id<<FK>>
  comment
  created_at
  updated_at
}

categories ||--{ category_item
conditions ||--o{ items
items ||--{ category_item
items ||--o{ likes
items ||--|| purchases
items ||--o{ comments
items }o--|| users
users ||--o{ purchases
users ||--o{ likes
users ||--o{ comments
purchases }--|| payment_methods

@enduml